# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ac026a77-5d9a-4d27-b971-6dcc190c51db";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  boot.initrd.luks.devices."2d0ee895-e992-4dd3-8b7a-f1099189bf02".device = "/dev/disk/by-uuid/2d0ee895-e992-4dd3-8b7a-f1099189bf02";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ac026a77-5d9a-4d27-b971-6dcc190c51db";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/ac026a77-5d9a-4d27-b971-6dcc190c51db";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/187E-4DAF";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ccdfc6d3-e2a5-4096-85e5-8ca03b309ab1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}