# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9fae7dfb-c8cf-49ca-b1ab-2562382300c0";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  boot.initrd.luks.devices."9d0086df-f8ac-416b-b891-6f052295efa2".device = "/dev/disk/by-uuid/9d0086df-f8ac-416b-b891-6f052295efa2";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9fae7dfb-c8cf-49ca-b1ab-2562382300c0";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/9fae7dfb-c8cf-49ca-b1ab-2562382300c0";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8EB5-DF1C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/59213f3d-166c-46bd-b87e-18502936a84c"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
