# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { device = "/dev/mapper/vg-btrfs"; fsType = "btrfs"; options = [ "subvol=@root" ]; };

  fileSystems."/var" = { device = "/dev/mapper/vg-btrfs"; fsType = "btrfs"; options = [ "subvol=@var" ]; };

  fileSystems."/home" = { device = "/dev/mapper/vg-btrfs"; fsType = "btrfs"; options = [ "subvol=@home" ]; };

  fileSystems."/opt" = { device = "/dev/mapper/vg-btrfs"; fsType = "btrfs"; options = [ "subvol=@opt" ]; };

  fileSystems."/srv" = { device = "/dev/mapper/vg-btrfs"; fsType = "btrfs"; options = [ "subvol=@srv" ]; };

  fileSystems."/boot" = { device = "/dev/disk/by-uuid/6234-EEC9"; fsType = "vfat"; };

  swapDevices = [ { device = "/dev/disk/by-uuid/6454e87d-0009-464a-8621-accdb6e46c27"; } ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
